### ISSUE TITLE
Unable to use code-review-forge-pr-at-point

### ISSUE THREAD

**Issue by drachul** [wandersoncferreira/code-review#117]
**Describe the bug**
I've configured code-review and my github enterprise account to make use of a personal access token.  The entry in the authinfo.gpg file is nearly a mirror of that for the forge one (except with ^code-review instead of ^forge, and with a different access token.)
If I open up the pull request list for a repository and try to run `M-x code-review-forge-pr-at-point` it just brings up the error `"Required Github token.  Look at the README for how to setup your Personal Access Token"`.

**To Reproduce**
1. Open magit buffer for repository
2. forge-pull
3. Open pull requests
4. Cursor to a specific pull request, and run `code-review-forge-pr-at-point`

**Expected behavior**
The code-review to open with the specified PR

**Desktop:**
 - MacOS 11.6.1
 - Emacs 27.2
 - code-review from Melpa 20211209.159

**Comment by wandersoncferreira** [comment]
@drachul can you try to change the value of `code-review-github-host` to match the one of your enterprise? The default value is`api.github.com` and thus the package will look for a `machine api.github.com login LOGIN^code-review password PWD` in the authinfo file. If your file is correctly configured you do have the enterprise host in there too so the package cannot find the auth.

The error message is a bit misleading though.

**Comment by drachul** [comment]
Thank you for the info, I've set that variable but now I seem to get another error when I try to use `code-review-forge-pr-at-point`: `deferred error : (wrong-type-argument sequencep listp)`

I have the variable set as such: `(setq code-review-github-host "my.ghe.host/api/v3")` and this is the host I have defined in my authinfo file.

**Comment by wandersoncferreira** [comment]
@drachul what is the log msg in the `~/.emacs.d/code-review-error.log` file?

**Comment by drachul** [comment]
```

Sat Dec 11 11:39:55 2021 - code-review--build-buffer - (wrong-type-argument listp error)
```

**Comment by wandersoncferreira** [comment]
yeah, not useful. If you can bear with me to fix this I will be very happy bc I can't actually test the solution in an enterprise environment myself.

can you try to execute this code in your `*scratch*` buffer:

```emacs-lisp
(ghub-get (format "/repos/%s/%s/commits/%s" OWNER REPO-NAME COMMIT-SHA)
              nil
              :unpaginate t
              :headers code-review-github-diffheader
              :auth 'code-review
              :host "my.ghe.host/api/v3")
```

and fill in the appropriate values for your owner, repo-name and commit-sha. I want to eliminate the possibility that we are building the wrong URL to the enterprise server in order to request the data.

**Comment by drachul** [comment]
Actually, I restarted my emacs client and now it seems to be working.  I'm not sure if something was cached incorrectly or what happened, but it seems to be working now?

To answer your question though, after running that bit (I assume with `M-x eval-buffer`? sorry I'm not very familiar with elisp) I get no output.

**Comment by wandersoncferreira** [comment]
If it's working then the code above succeeded. Great news :) let me know if something else pops up. Can I close the issue?

**Comment by drachul** [comment]
Yes it can be closed, thank you very much for the assistance and thanks for this package, I will get lots of use out of it! :)
