### ISSUE TITLE
[GitLab] Support for project groups

### ISSUE THREAD

**Issue by muffinmad** [wandersoncferreira/code-review#123]
Hi!

Projects on GitLab can be organized into groups, e.g. MR URL can look like this
```
https://gitlab.com/owner/group/subgroup/project/-/merge_requests/1
```

The `code-review-utils-pr-from-url` can't handle project groups. Evaluating
```elisp
(code-review-utils-pr-from-url
 "https://gitlab.com/owner/group/subgroup/project/-/merge_requests/1")
```
will result in
```
((num . "1") (repo . "project") (owner . "subgroup") (forge . gitlab) (url . "https://gitlab.com/owner/group/subgroup/project/-/merge_requests/1"))
```
In this case `owner` shoud be `"owner"` and `repo` should be `"group%2Fsubgroup%2Fproject"`.

Thanks!

**Comment by wandersoncferreira** [comment]
@muffinmad I created a subgroup in my Gitlab account used for testing purpose and the URL structure is a little different:
https://gitlab.com/code-review-experiment/first-group/i-never-used-spring-hurray/-/merge_requests/1

We have "https://gitlab.com/owner/subgroup/project/-/merge_requests/1" the distinction between "group" and "subgroup" in your comment couldn't be verified. Navigating through the URLs in the gitlab page seems like the concept of "owner" is called "group".

could you confirm this? The #128 already supports the structure I mentioned and I only want to add a new test case and confirm what I've said here before merging.

Thanks for reporting

**Comment by muffinmad** [comment]
@wandersoncferreira I've leave a comment in your PR almost at the same time :)

According to [GitLab docs](https://docs.gitlab.com/ee/user/group/subgroups/) there can be up to 20 levels of subgroups. I propose to not limit the number of groups/subgroups in URL pattern.

IMO this should work:
```
https://gitlab.com/<owner>/<all the chars including '/' is going to project>/-/merge_requests/1
```

**Comment by wandersoncferreira** [comment]
Seems perfect to me, I will change the code and add some test cases.

**Comment by wandersoncferreira** [comment]
@muffinmad please reopen if something else pops up! thanks for the review!

**Comment by muffinmad** [comment]
@wandersoncferreira FYI checked this out and it works as expected. Thanks!
