### ISSUE TITLE
No comments in review/unable to approve ('lgtm' shortcut)

### ISSUE THREAD

**Issue by drachul** [wandersoncferreira/code-review#125]
**Describe the bug**
When I perform a code review with a PR that has been opened (with `code-review-forge-pr-at-point`), the code review is opened (with diffs), no comments are seen in the PR (though there are many in the actual PR)

After trying to approve the PR with the shortcut `l` I get the message:

`PR have CI issues.  Do you want to proceed? (y or n)`

If I select `y`, I get the following error:

```
Invalid request.

For 'properties/commit_id', nil is not a string.
```

The contents of the code-review-error.log:

```
Mon Dec 13 10:36:51 2021 - code-review-github-errback - ((error http 422 ((message . "Invalid request.

For 'properties/commit_id', nil is not a string.") (documentation_url . "https://docs.github.com/enterprise/3.0/rest/reference/pulls#create-a-review-for-a-pull-request"))) (("Server" . "GitHub.com") ("Date" . "Mon, 13 Dec 2021 18:36:51 GMT") ("Content-Type" . "application/json; charset=utf-8") ("Content-Length" . "199") ("X-OAuth-Scopes" . "repo, write:discussion") ("X-GitHub-Enterprise-Version" . "3.0.15") ("X-GitHub-Media-Type" . "github.v3; format=json") ("Access-Control-Expose-Headers" . "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset") ("Access-Control-Allow-Origin" . "*") ("X-GitHub-Request-Id" . "**redacted**") ("Strict-Transport-Security" . "max-age=31536000; includeSubdomains") ("X-Frame-Options" . "deny") ("X-Content-Type-Options" . "nosniff") ("X-XSS-Protection" . "1; mode=block") ("Referrer-Policy" . "origin-when-cross-origin, strict-origin-when-cross-origin") ("Content-Security-Policy" . "default-src 'none'") ("X-Runtime-Rack" . "0.088824")) (:error (error http 422 ((message . "Invalid request.

For 'properties/commit_id', nil is not a string.") (documentation_url . "https://docs.github.com/enterprise/3.0/rest/reference/pulls#create-a-review-for-a-pull-request"))) :peer (:certificates ((:version 3 :serial-number "**redacted**" :issuer "C=GB,ST=Greater Manchester,L=Salford,O=Sectigo Limited,CN=Sectigo RSA Organization Validation Secure Server CA" :valid-from "2020-05-30" :valid-to "2022-05-30" :subject "**redacted**" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "**redacted**" :certificate-id "**redacted**" :pem "-----BEGIN CERTIFICATE-----
```
followed by a number of certificates then
```
#s(ghub--req #s(url "https" nil nil "**<github enterprise domain>**" nil "**<repository path to PR>**" nil nil t nil t t) nil nil "POST" #[0 "\302\305=\203\306\307\301\303\242\"B\300\242B\207\310\301\302\303\242\304$\300\242B\207" [((("Content-Type" . "application/json"))) "**<github enterprise api uri>**" code-review ("**<github enterprise username>**") nil basic "Authorization" ghub--basic-auth ghub--auth] 5] ghub--handle-response nil t nil #[128 "\303\304\300\305\303#\210\304\300\306\307 #\210\310\300!\210\311
\312\313#)\207" [#s(#s(eieio--class code-review-github-repo nil (#s(eieio--class code-review-db-pullreq nil (#s(eieio--class closql-object nil nil [#s(cl-slot-descriptor closql-database nil t nil)] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (closql-database 0)) (code-review-db-pullreq code-review-db-comment code-review-db-path code-review-db-buffer forge-object) ((:closql-database . closql-database)) [#s(cl-slot-descriptor closql-order-by nil t nil) #s(cl-slot-descriptor closql-foreign-key nil t nil) #s(cl-slot-descriptor closql-primary-key nil t nil) #s(cl-slot-descriptor closql-table nil t nil) #s(cl-slot-descriptor closql-class-suffix nil t nil) #s(cl-slot-descriptor closql-class-prefix nil t nil)] [nil nil nil nil nil nil] #s(#9 nil) (:custom-groups nil :abstract t))) [#s(cl-slot-descriptor closql-database nil t nil) #s(cl-slot-descriptor id unbound t nil) #s(cl-slot-descriptor finished nil t nil) #s(cl-slot-descriptor finished-at nil t nil) #s(cl-slot-descriptor saved nil t nil) #s(cl-slot-descriptor saved-at nil t nil) #s(cl-slot-descriptor raw-infos nil t nil) #s(cl-slot-descriptor raw-diff nil t nil) #s(cl-slot-descriptor raw-comments nil t nil) #s(cl-slot-descriptor owner unbound t nil) #s(cl-slot-descriptor repo unbound t nil) #s(cl-slot-descriptor number unbound t nil) #s(cl-slot-descriptor description nil t nil) #s(cl-slot-descriptor title nil t nil) #s(cl-slot-descriptor host nil t nil) #s(cl-slot-descriptor sha nil t nil) #s(cl-slot-descriptor feedback nil t nil) #s(cl-slot-descriptor state nil t nil) #s(cl-slot-descriptor replies nil t nil) #s(cl-slot-descriptor review nil t nil) #s(cl-slot-descriptor labels nil t nil) #s(cl-slot-descriptor merge nil t nil) #s(cl-slot-descriptor milestones nil t nil) #s(cl-slot-descriptor projects nil t nil) #s(cl-slot-descriptor reviewers nil t nil) #s(cl-slot-descriptor assignees nil t nil) #s(cl-slot-descriptor linked-issues nil t nil) #s(cl-slot-descriptor buffer unbound t ((:closql-class . code-review-db-buffer)))] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (closql-database 0 id 1 finished 2 finished-at 3 saved 4 saved-at 5 raw-infos 6 raw-diff 7 raw-comments 8 owner 9 repo 10 number 11 description 12 title 13 host 14 sha 15 feedback 16 state 17 replies 18 review 19 labels 20 merge 21 milestones 22 projects 23 reviewers 24 assignees 25 linked-issues 26 buffer 27)) (code-review-gitlab-repo code-review-github-repo) ((:closql-database . closql-database) (:id . id) (:owner . owner) (:repo . repo) (:number . number)) [#s(cl-slot-descriptor closql-class-prefix "code-review-" t nil) #s(cl-slot-descriptor closql-class-suffix nil t nil) #s(cl-slot-descriptor closql-table 'pullreq t nil) #s(cl-slot-descriptor closql-primary-key 'id t nil) #s(cl-slot-descriptor closql-foreign-key nil t nil) #s(cl-slot-descriptor closql-order-by [(desc number)] t nil)] ["code-review-" nil pullreq id nil [(desc number)]] #s(#7 nil unbound nil nil nil nil nil nil nil unbound unbound unbound nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil unbound) (:custom-groups nil :abstract t))) [#s(cl-slot-descriptor closql-database nil t nil) #s(cl-slot-descriptor id unbound t nil) #s(cl-slot-descriptor finished nil t nil) #s(cl-slot-descriptor finished-at nil t nil) #s(cl-slot-descriptor saved nil t nil) #s(cl-slot-descriptor saved-at nil t nil) #s(cl-slot-descriptor raw-infos nil t nil) #s(cl-slot-descriptor raw-diff nil t nil) #s(cl-slot-descriptor raw-comments nil t nil) #s(cl-slot-descriptor owner unbound t nil) #s(cl-slot-descriptor repo unbound t nil) #s(cl-slot-descriptor number unbound t nil) #s(cl-slot-descriptor description nil t nil) #s(cl-slot-descriptor title nil t nil) #s(cl-slot-descriptor host nil t nil) #s(cl-slot-descriptor sha nil t nil) #s(cl-slot-descriptor feedback nil t nil) #s(cl-slot-descriptor state nil t nil) #s(cl-slot-descriptor replies nil t nil) #s(cl-slot-descriptor review nil t nil) #s(cl-slot-descriptor labels nil t nil) #s(cl-slot-descriptor merge nil t nil) #s(cl-slot-descriptor milestones nil t nil) #s(cl-slot-descriptor projects nil t nil) #s(cl-slot-descriptor reviewers nil t nil) #s(cl-slot-descriptor assignees nil t nil) #s(cl-slot-descriptor linked-issues nil t nil) #s(cl-slot-descriptor buffer unbound t ((:closql-class . code-review-db-buffer))) #s(cl-slot-descriptor callback nil t nil)] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (closql-database 0 id 1 finished 2 finished-at 3 saved 4 saved-at 5 raw-infos 6 raw-diff 7 raw-comments 8 owner 9 repo 10 number 11 description 12 title 13 host 14 sha 15 feedback 16 state 17 replies 18 review 19 labels 20 merge 21 milestones 22 projects 23 reviewers 24 assignees 25 linked-issues 26 buffer 27 callback 28)) nil ((:closql-database . closql-database) (:id . id) (:owner . owner) (:repo . repo) (:number . number)) [#s(cl-slot-descriptor closql-order-by [(desc number)] t nil) #s(cl-slot-descriptor closql-foreign-key nil t nil) #s(cl-slot-descriptor closql-primary-key 'id t nil) #s(cl-slot-descriptor closql-table 'pullreq t nil) #s(cl-slot-descriptor closql-class-suffix nil t nil) #s(cl-slot-descriptor closql-class-prefix "code-review-" t nil)] [[(desc number)] nil id pullreq nil "code-review-"] #s(#5 nil unbound nil nil nil nil nil nil nil unbound unbound unbound nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil unbound nil) (:custom-groups nil)) #s(code-review-db-database #<process emacsql-sqlite<1>> #<buffer  *emacsql-log*-34170> #<finalizer> "/Users/<username>/.emacs.d/code-review-db-file.sqlite") "**redacted**" nil nil nil nil nil
```
followed by a bunch of diffs.

Sensitive items I've replaced with `**...**` in its place

**To Reproduce**
1. Open review for PR
2. Review diffs
3. `r` followed by `l`

**Expected behavior**
PRs to show previously created comments within the PR, and for the approval to complete successfully.

**Version:**
 - code-review 20211212.1051 from melpa

**Additional context**
Running on a corporate github enterprise repository.

**Comment by wandersoncferreira** [comment]
@drachul thanks for the detailed report, unfortunately I can't directly access an enterprise edition of Github right now but if you can help me find what is going on here I would be very happy.

1. If you do not see any comments but you see the diff this seems like an issue with `scopes`. Which scopes do you have setup?
2. `'properties/commit_id'` being nil could also be an issue with gathering data without proper scopes from the GraphQL interface. Seems like all the data that comes from the GraphQL is not working properly. I found this issue in the `forge` repository https://github.com/magit/forge/issues/174#issuecomment-515510414 that might be related. What is the structure of your enterprise URL for GraphQL? Do you know that?


I captured some improvements already from this brief investigation: i) add a `code-review-github-graphql-host` variable, ii) improve error handling on the data coming from GraphQL when required data is missing, iii) make it more explicit in the codebase what is required data ^^.

So much thing to work on o.O
Thanks again, let me know about the points above.

**Comment by drachul** [comment]
> @drachul thanks for the detailed report, unfortunately I can't directly access an enterprise edition of Github right now but if you can help me find what is going on here I would be very happy.
> 
>     1. If you do not see any comments but you see the diff this seems like an issue with `scopes`. Which scopes do you have setup?

For the access token I used for `code-review` I have all of `repo`, and `write:discussion` (which automatically enables `read:discussion` as well)

> 
>     2. `'properties/commit_id'` being nil could also be an issue with gathering data without proper scopes from the GraphQL interface. Seems like all the data that comes from the GraphQL is not working properly. I found this issue in the `forge` repository [Cookies must be enabled to use GitHub magit/forge#174 (comment)](https://github.com/magit/forge/issues/174#issuecomment-515510414) that might be related. What is the structure of your enterprise URL for GraphQL? Do you know that?
> 

The url I've specified in the authinfo file is `<host>/api/v3`, but this is REST I believe and not GraphQL.  According to some docs I read the GraphQL API exists on `<host>/api/graphql`, however I'm not specifying this anywhere, should I be?

> So much thing to work on o.O Thanks again, let me know about the points above.
>
Thank you for all your hard work!

**Comment by drachul** [comment]
So I've set the `code-review-github-graphql-host` value, and it asked me to provide a username, so I did, but it's saying I need to setup a personal access token.  Do I need to create a separate authinfo entry for the code-review graphql?

**Comment by wandersoncferreira** [comment]
> So I've set the `code-review-github-graphql-host` value, and it asked me to provide a username, so I did, but it's saying I need to setup a personal access token. Do I need to create a separate authinfo entry for the code-review graphql?

Oh jeez.. `ghub` package makes a lookup in the `authinfo` file based on the host .. so if you have different hosts, it means different tokens :/

Could you make the additional setup to see if the main issue is gone? I need to look at this more close to find a way to avoid this duplication if possible.

**Comment by drachul** [comment]
I created the extra entry in authinfo for the graphql host (though it seems I needed to specify `<host>/api` and not `<host>/api/graphql`, because something seemed to be adding `/graphql` on the end), and now I seem to be back where I was initially.  I can open the code review for the PR, but I still don't see any comments.

Just as a test, I created another test token, and enabled all of the scopes, but that also didn't seem to have any effect.

**Comment by wandersoncferreira** [comment]
Can you setup the GraphQL explorer in your machine as informed here https://docs.github.com/en/enterprise-server@3.0/graphql/guides/using-the-explorer and execute this GraphQL query ?

```
{
  repository(name: "tempo", owner: "eval-all-software") {
    pullRequest(number: 148) {
      reviews(first: 50) {
        nodes {
          typename: __typename
          author {
            login
          }
          bodyHTML
          state
          createdAt
          databaseId
          updatedAt
          comments(first: 50) {
            nodes {
              createdAt
              updatedAt
              bodyHTML
              originalPosition
              diffHunk
              position
              outdated
              path
              databaseId
              reactions(first: 50) {
                nodes {
                  id
                  content
                }
              }
            }
          }
        }
      }
    }
  }
}
```

(the same as the package does to get the comments from the PR..) this way we can remove all the emacs-related things away. Thank you for all this help troubleshooting this.

**Comment by drachul** [comment]
Ok, I managed to get GraphiQL up and running, configured it with my token, and ran the query you gave me (with updates for my particular repo/PR) and it returns a large JSON-encoded string with a bunch of metadata including comments.

**Comment by wandersoncferreira** [comment]
> Ok, I managed to get GraphiQL up and running, configured it with my token, and ran the query you gave me (with updates for my particular repo/PR) and it returns a large JSON-encoded string with a bunch of metadata including comments.

I'm running out of ideas for why you can't see the comments being rendered in the buffer. The data seems to be coming through as expected. Can you do a clean restart in emacs and try again? :/ also look at the value of `code-review-section-grouped-comments` through `C-h v`

**Comment by drachul** [comment]
I've tried restarting a few times, no luck there.
The valued of the `code-review-section-grouped-comments` is `nil`.

I'll keep playing around with it and maybe I'll find something, perhaps it's some incompatibility with spacemacs.

**Comment by drachul** [comment]
Well, I can confirm it has nothing to do with the spacemacs distribution I use, as I tried loading up a completely fresh emacs config with only installing magit, forge, code-review, and after getting it all configured, the code-review for the PR still do not show comments.

Just for my own curiosity I opened up the `code-review-db-file.sqlite` file and found that the `comment` table was empty (whereas the other tables are populated).

Some other observations: there are no commits listed in the code-review PR, nor are there reviewers, however these obviously also exist in the actual PR.

**Comment by wandersoncferreira** [comment]
I really appreciate your efforts on this @drachul . Unfortunately I can't dig deeper, but I can add more checks&invariants to try to throw the error and spot what is going on.

But if you feel yet more adventurous and want to debug the source code I can answer any question about the structure of the project. For instance, there is a giant GraphQL query that returns all these data that you are missing https://github.com/wandersoncferreira/code-review/blob/1bae1441ebbb30398611bf450be81293a4cbfffe/code-review-github.el#L158 and the result from Github can be seem here https://github.com/wandersoncferreira/code-review/blob/1bae1441ebbb30398611bf450be81293a4cbfffe/code-review.el#L219

this is a good first place to see if you received all the data from GitHub. If you look at the `raw-infos` variable and all the data is there, e.g. `properties/commit_id` is `headRef { target{ oid } }` in the GraphQL or `(let-alist raw-infos .headRef.target.oid)`, then we can discard any issues querying it and looking for errors elsewhere in the codebase for example this place add the commits https://github.com/wandersoncferreira/code-review/blob/1bae1441ebbb30398611bf450be81293a4cbfffe/code-review-section.el#L828 then if there is nothing in there probably nothing comes from Github because we access `(let-alist raw-infos .commits.nodes)` directly to build the section.

**Comment by wandersoncferreira** [comment]
@drachul I added some logs with the received value from GitHub GraphQL API. could you try with the latest commit and see what gets logged in the `code-review-log-file`?

**Comment by drachul** [comment]
Here's the contents of the `code-review-error.log`:

```

Tue Dec 14 16:59:40 2021 - code-review--internal-build - Data returned by GraphQL API:
 nil

Tue Dec 14 16:59:42 2021 - code-review--internal-build - Commit SHA not returned by GraphQL Github API. See `code-review-log-file' for details

Tue Dec 14 16:59:42 2021 - code-review--internal-build - Data returned by GraphQL API:
 nil

Tue Dec 14 16:59:42 2021 - code-review--build-buffer - (error "Missing required data")
```

I tried running the graphql query shown here: https://github.com/wandersoncferreira/code-review/blob/1bae1441ebbb30398611bf450be81293a4cbfffe/code-review-github.el#L158 manually, but it gives some error from the server:

```
{
  "errors": [
    {
      "path": [
        "query",
        "repository",
        "pullRequest",
        "commits",
        "nodes",
        "commit",
        "statusCheckRollup",
        "contexts",
        "nodes",
        "... on CheckRun",
        "checkSuite",
        "workflowRun"
      ],
      "extensions": {
        "code": "undefinedField",
        "typeName": "CheckSuite",
        "fieldName": "workflowRun"
      },
      "locations": [
        {
          "line": 98,
          "column": 23
        }
      ],
      "message": "Field 'workflowRun' doesn't exist on type 'CheckSuite'"
    }
  ]
}
```

**Comment by wandersoncferreira** [comment]
Hoho! Finally! thanks @drachul . If we compare the schemas defined for the enterprise 3.0 version here https://docs.github.com/en/enterprise-server@3.0/graphql/overview/public-schema and the free host version here https://docs.github.com/en/graphql/overview/public-schema we can see the differences in schema indeed!


Possible fixes:

1. Do not support any enterprise edition older than 3.3 and say thanks for all the fish @drachul 
2. Have a minimal compatible graphql query to be run if the complete one fails

**Comment by drachul** [comment]
Given that this version of github enterprise seems to be slated for discontinuation in early 2022, I would say it's probably not worthwhile to really go out of your way to support the older services.

Hopefully my employer is planning to upgrade in the near future, and then I can go back to working with code-review :)

**Comment by wandersoncferreira** [comment]
> Given that this version of github enterprise seems to be slated for discontinuation in early 2022, I would say it's probably not worthwhile to really go out of your way to support the older services.
> 
> Hopefully my employer is planning to upgrade in the near future, and then I can go back to working with code-review :)

you should have said that 20 min ago.. I am merging the fix to support a fallback query. This might be very useful concept for the future of this package as there are multiple versions of the GraphQL that might have other nuances as this one.

**Comment by wandersoncferreira** [comment]
if you can test the latest commit and report back how it goes will be great!

**Comment by drachul** [comment]
Ok ran another code review and got: `Got an error from your VC provider.  Check 'code-review-log-file'`

Output of `code-review-error.log`
```
Tue Dec 14 18:12:09 2021 - code-review--internal-build - Data returned by GraphQL API:
 (((message . "**DIFF HUNKS**") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors")) ((errors ((path "query" "repository" "pullRequest" "commits" "nodes" "commit" "statusCheckRollup" "contexts" "nodes" "... on CheckRun" "checkSuite" "workflowRun") (extensions (code . "undefinedField") (typeName . "CheckSuite") (fieldName . "workflowRun")) (locations ((line . 98) (column . 23))) (message . "Field 'workflowRun' doesn't exist on type 'CheckSuite'")))) ((data (repository (pullRequest (id . "**redacted**") (headRef) (baseRefName . "dev") (headRefName . "**redacted**") (isDraft) (databaseId . 400666) (number . 29) (createdAt . "2021-12-09T01:17:39Z") (updatedAt . "2021-12-09T01:26:37Z") (latestOpinionatedReviews (nodes ((author (login . "**redacted**")) (createdAt . "2021-12-09T01:25:56Z") (state . "APPROVED")))) (reviewRequests (nodes)) (files (nodes ((path . "**redacted**") (additions . 2) (deletions . 2)) ((path . "**redacted**") (additions . 39) (deletions . 5)))) (milestone) (labels (nodes)) (assignees (nodes)) (projectCards (nodes)) (suggestedReviewers) (commits (totalCount . 1) (nodes ((commit (abbreviatedOid . "**redacted**") (message . "**redacted**") (statusCheckRollup (state . "SUCCESS") (contexts (nodes nil nil))))))) (title . "**redacted**") (state . "MERGED") (bodyHTML . "**redacted**") (bodyText . "**redacted**") (reactions (nodes)) (comments (nodes)) (reviews (nodes ((typename . "PullRequestReview") (author (login . "**redacted**")) (bodyHTML . "<p>LGTM</p>") (state . "APPROVED") (createdAt . "2021-12-09T01:25:56Z") (databaseId . 951219) (updatedAt . "2021-12-09T01:25:56Z") (comments (nodes))))))))))

Tue Dec 14 18:12:11 2021 - code-review--internal-build - Commit SHA not returned by GraphQL Github API. See `code-review-log-file' for details

Tue Dec 14 18:12:11 2021 - code-review--internal-build - Data returned by GraphQL API:
 (((message . "**DIFF HUNKS**") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors")) ((errors ((path "query" "repository" "pullRequest" "commits" "nodes" "commit" "statusCheckRollup" "contexts" "nodes" "... on CheckRun" "checkSuite" "workflowRun") (extensions (code . "undefinedField") (typeName . "CheckSuite") (fieldName . "workflowRun")) (locations ((line . 98) (column . 23))) (message . "Field 'workflowRun' doesn't exist on type 'CheckSuite'")))) ((data (repository (pullRequest (id . "**redacted**") (headRef) (baseRefName . "dev") (headRefName . "**redacted**") (isDraft) (databaseId . 400666) (number . 29) (createdAt . "2021-12-09T01:17:39Z") (updatedAt . "2021-12-09T01:26:37Z") (latestOpinionatedReviews (nodes ((author (login . "**redacted**")) (createdAt . "2021-12-09T01:25:56Z") (state . "APPROVED")))) (reviewRequests (nodes)) (files (nodes ((path . "**redacted**") (additions . 2) (deletions . 2)) ((path . "**redacted**") (additions . 39) (deletions . 5)))) (milestone) (labels (nodes)) (assignees (nodes)) (projectCards (nodes)) (suggestedReviewers) (commits (totalCount . 1) (nodes ((commit (abbreviatedOid . "**redacted**") (message . "**redacted**") (statusCheckRollup (state . "SUCCESS") (contexts (nodes nil nil))))))) (title . "**redacted**") (state . "MERGED") (bodyHTML . "**redacted**") (bodyText . "**redacted**") (reactions (nodes)) (comments (nodes)) (reviews (nodes ((typename . "PullRequestReview") (author (login . "**redacted**")) (bodyHTML . "<p>LGTM</p>") (state . "APPROVED") (createdAt . "2021-12-09T01:25:56Z") (databaseId . 951219) (updatedAt . "2021-12-09T01:25:56Z") (comments (nodes))))))))))

Tue Dec 14 18:12:11 2021 - code-review--build-buffer - (error "Missing required data")

**Comment by wandersoncferreira** [comment]
@drachul this seems to be a bug when the branch under review was already deleted. Is this the case? merge fixed to use `headRefOid` value which the graphql docs says:

```
 """
  Identifies the oid of the head ref associated with the pull request, even if the ref has been deleted.
  """
  headRefOid: GitObjectID!

```

**Comment by drachul** [comment]
Ah yes, sorry I didn't think about that, this was a PR already merged that I just picked since it was a smaller PR (our git hooks automatically delete the branch once it's been merged.)

I just tried it with a different (active) PR and I can see comments now!

**Comment by drachul** [comment]
Saw the update and re-tried with the merged PR that was failing before, and that works now!

**Comment by wandersoncferreira** [comment]
Great, thank you for this long journey!
