### ISSUE TITLE
Strange headline indentation

### ISSUE THREAD

**Issue by fuzzycode** [wandersoncferreira/code-review#145]
## What was wrong:
When collapsing a headline, the headline after it will be indented what look like one tab stop. When expanding the headline the indentation is removed again.

Not all headlines are affected but collapsing the description headline will cause the "Your Review Feedback" heading to be indented.

### Collapsed
<img width="490" alt="" src="https://user-images.githubusercontent.com/1155261/146639064-9b9961f9-281a-4241-8c8c-5224225264e3.png">

### Expanded
<img width="489" alt="" src="https://user-images.githubusercontent.com/1155261/146639089-7c0a4c56-da81-4dd7-9dad-a4dde8b1b1e0.png">

## What do you expect:
The headlines should never be indented and should stay left aligned at all times.

## Details:
Code-review is at ~b0bedbdb30e019ed8c40fedf1087c3ad28e72c59b0bedbdb30e019ed8c40fedf1087c3ad28e72c59~ 582c76cf9212131ad1476f43fd765c4cceda4051 running OSX Monterey on a M1 Pro, using DoomEmacs.

**Comment by wandersoncferreira** [comment]
Thanks for reporting @fuzzycode , are you reviewing a PR from GitHub or Gitlab?

**Comment by fuzzycode** [comment]
It is a github PR that I am using for testing
https://github.com/fuzzycode/doom.d/pull/2
