### ISSUE TITLE
Broken indentation

### ISSUE THREAD

**Issue by fuzzycode** [wandersoncferreira/code-review#149]
#145 is partially solved but some glitches still remain.

Expanding/collapsing in the conversation section work as expected but contracting "Description" is still broken.

There is also an issue with expanding the Description when set up like in the picture. If Pressing TAB with point on the Description heading it will not expand and I get the error "_hs-grok-mode-type: Code Review Mode doesn’t support Hideshow Minor Mode_.

<img width="467" alt="" src="https://user-images.githubusercontent.com/1155261/146652832-080632d1-66e5-4afe-b796-3c736323943b.png">

**Comment by wandersoncferreira** [comment]
could you verify with the latest commit? I tested on my side and things were good! thanks

**Comment by fuzzycode** [comment]
Yes, the last fix solves all known issues with indentation and you can close this bug. Thanks for looking in to it!
