### ISSUE TITLE
Github: Ability to review a PR without leaving a feedback message

### ISSUE THREAD

**Issue by ktfleming** [wandersoncferreira/code-review#189]
In the Github web UI, you can review a PR by adding various comments on particular changes, and then submitting the review (choosing the "comment" option) without writing a specific feedback message -- just leaving the comment text area blank.

In `code-review` though, trying to submit the review (via `r c`) without feedback results in the error "You must provide a feedback msg before submit your Review."

Would it be possible to allow submitting review with no feedback message, just individual comments, as it seems that Github allows this?

**Comment by ktfleming** [comment]
Trying this locally, changing `code-review--submit-feedback-required?`:

```diff
diff --git a/code-review-actions.el b/code-review-actions.el
index 6b1c549..2b80774 100644
--- a/code-review-actions.el
+++ b/code-review-actions.el
@@ -95,7 +95,8 @@
   (and (not (oref review-obj feedback))
        (not (string-equal (oref review-obj state) "APPROVE"))
        (not (and (string-equal (oref review-obj state) "COMMENT")
-                 (code-review-gitlab-repo-p (oref review-obj pr))))))
+                 (or (code-review-github-repo-p (oref review-obj pr))
+                     (code-review-gitlab-repo-p (oref review-obj pr)))))))
 
 ;;;###autoload
 (defun code-review--submit (event &optional feedback only-reply?)
```

seems to make the feedback-less review work for Github, perhaps that's all that's needed?

**Comment by wandersoncferreira** [comment]
Yes @ktfleming , this is all needed. Could you open a PR with this change?

I already tackled this issue some time ago and I remember that only the APPROVE option was possible to send without a feedback message. But I tried again today and you are right. I might be sleeping :/

Thanks for looking into it.

**Comment by ktfleming** [comment]
Sure, I’ll open a PR soon when I’m back at my PC!

**Comment by ktfleming** [comment]
Created: https://github.com/wandersoncferreira/code-review/pull/190
