### ISSUE TITLE
[github enterprise] "Files changed" shows an HTML login page

### ISSUE THREAD

**Issue by logc** [wandersoncferreira/code-review#199]
**Describe the bug**
"Review pull request" from Magit status buffer on any PR. The PR buffer opens, and general information is correct, but the "Files changed" part always shows an HTML page; if rendered in a browser, it asks for a login using LDAP. But authentication should have worked correctly using the token, otherwise the PR would not have been shown by Forge or downloaded by Code-review.

**To Reproduce**
1. Go to Magit status buffer
2. Type "@ c r" to start a PR review
3. Scroll down to 'Files changed'
4. See error as an HTML page

**Expected behavior**
The same diff that can be found on the PR using a browser.

**Screenshots**
This is the start of the relevant section in the PR buffer:

```
Your Review Feedback
Leave a comment here.

Conversation
Files changed (1 files; 1 additions, 1 deletions)
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">

<!-- ... lots of other stuff ... -->

          <!-- '"` --><!-- </textarea></xmp> --></option></form><form action="/session" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="" />  <label for="login_field">
    Username
  </label>
  <input type="text" name="login" id="login_field" class="form-control input-block" autocapitalize="off" autocorrect="off" autocomplete="username" autofocus="autofocus" />

  <div class="position-relative">
    <label for="password">
      Password
    </label>
    <input type="password" name="password" id="password" class="form-control form-control input-block" autocomplete="current-password" />
    <input type="hidden" name="trusted_device" id="trusted_device" class="form-control" />
    <input type="hidden" class="js-webauthn-support" name="webauthn-support" value="unknown">
<input type="hidden" class="js-webauthn-iuvpaa-support" name="webauthn-iuvpaa-support" value="unknown">
<input type="hidden" name="return_to" id="return_to" value="https://ghe.company.net/api/repos/org/repo/pulls/1" class="form-control" />


    <input type="submit" name="commit" value="Sign in" class="btn btn-primary btn-block" data-disable-with="Signing in…" />

    
  </div>
</form>

<!-- and the rest of the page ... -->
```

**Desktop:**
 - OS: mac OS Catalina 10.15.7
 - Browser: Emacs
 - Version: 27.2

**Additional context**
Reviewing the file `code-review-error.log`, the response from Github Enterprise seems to have some correct diff, but it is for another PR and is not displayed by the package. I would share it on this issue but I think I should anonymise some of its contents first.

**Comment by luskwater** [comment]
I have the same (or similar) result, also with Github Enterprise.
In the returned errors, I have 
```
(errors
   ((path "query" "repository" "pullRequest" "commits" "nodes" "commit" "statusCheckRollup" "contexts" "nodes" "... on CheckRun" "checkSuite" "workflowRun")
    (extensions (code . "undefinedField") (typeName . "CheckSuite") (fieldName . "workflowRun"))
    (locations ((line . 105) (column . 23)))
    (message . "Field 'workflowRun' doesn't exist on type 'CheckSuite'")))
```

Now, if in `code-review--build-buffer` I avoid using the `code-review-github-graphql-complete` query by replacing 
```
          (deferred:parallel
            (lambda () (code-review-diff-deferred obj))
            (lambda () (code-review-infos-deferred obj))
            (lambda () (code-review-infos-deferred obj t)))
```

with
```
          (deferred:parallel
            (lambda () (code-review-diff-deferred obj))
            (lambda () (code-review-infos-deferred obj t)) ; Force fallback query
            (lambda () (code-review-infos-deferred obj t)))
```

so that it uses `code-review-github-graphql-fallback`, then I don't get the `checkSuite`/`workflowRun` errors (or any errors) in `code-review-errors.log`, but I still get the same HTML in place of the diffs. 

Presumably, there's _something_ about the `ghub-graphql` call that causes the authentication problem, I guess.

**Comment by luskwater** [comment]
More from my somewhat misdirected notes above. The _Github Enterprise_ REST API does not seem to accept an `Authorization: token 0123456789ABCDE...` header using a personal access token. _GraphQL_ requests work fine, but I am unable to fetch the diffs. I've tried using `curl`:
```shell
curl --header "Authorization: token baddecafbaddecafbaddecafbaddecafbaddecafbaddecaf" \
    --header "Content-Type: application/json" \
    --header "Accept: application/vnd.github.v3.diff" \
    "https://myghe.server.com/api/repos/some-owner/some-repo/pulls/5432"
```
I still get the HTML for our login page.

If there's something here I'm missing, let me know, please.

**Comment by luskwater** [comment]
Just for laughs: I just viewed this issue _in_ `magit`/`forge`/`code-review`, and was concerned that I ran into the login problem, even on `github`: how could it prompt me for an enterprise login?

Then I realized I was looking at the problem-description provided by @logc with its HTML output. Whew!

**Comment by logc** [comment]
@luskwater : sorry, I missed your previous message about having found a solution. I just tried, and can confirm that it works!  Thank you so much! :smile:

Maybe you want to update [this package's docs for configuring Github Enterprise](https://github.com/wandersoncferreira/code-review/blob/master/docs/github.md)? I did that when I found out how to make it work for me ...

**Comment by wandersoncferreira** [comment]
> Maybe you want to update [this package's docs for configuring Github Enterprise](https://github.com/wandersoncferreira/code-review/blob/master/docs/github.md)? I did that when I found out how to make it work for me ...

Would be great to have a PR to add more documentation on this issue. Thanks for digging into it.

**Comment by wandersoncferreira** [comment]
I'm closing this issue. Thank you @luskwater  for all your efforts here.
