### ISSUE TITLE
deferred error : (wrong-type-argument listp 7) when opening code review

### ISSUE THREAD

**Issue by thermopyle** [wandersoncferreira/code-review#226]
**Describe the bug**
When I try to open a code review, I get `deferred error : (wrong-type-argument listp 7)` and the code review won't open.

**To Reproduce**
1. Do `code-review-forge-pr-at-point` at a PR in magit
2. Error: `(wrong-type-argument listp 7)`

**Expected behavior**
The code review should open in a new editor

**Desktop (please complete the following information):**
 - OS: macOS 12 .6 Monterey.
 - Emacs: 29.0.50 installed using homebrew.
 - Magit: magit-20221014.1745
 - code-review: 20220629.1215

**Comment by n0amso1** [comment]
Do you experience this on all code reviews or specific ones?
If the latter, can you link a sample PR that reproduces it?

I've experienced something similar before and considered trying fixing it,
so if I get the chance eventually I'd like to make sure that this one gets
resolved as well.

Thanks!

**Comment by thermopyle** [comment]
This happens with all PR's, I cannot open any of them. They're from GitHub, I might add. This started happening this week, I cannot say exactly when, but last week I review a number of PR's using code-review. I update Emacs every Monday, I think something happened in the update.

**Comment by thermopyle** [comment]
I completely removed all magit-*, forge and code-review packages and installed them again, it did not help.

**Comment by rlister** [comment]
I can recreate with PRs from this repo.

```
(code-review-start "https://github.com/wandersoncferreira/code-review/pull/224")
```

From messages:

```
#s(deferred deferred:default-callback #[257 "���!\"��!�\0��A@\"�\0��!���!�" [code-review-utils--log "code-review--build-buffer" prin1-to-string sequencep string-prefix-p "BUG: Unknown extended header:" message "Your PR might have diffs too large. Currently not supported." "Got an error from your VC provider. Check `code-review-log-file'."] 5 "
```

From `code-review-log-file`:

```
Wed Oct 19 19:07:49 2022 - code-review--build-buffer - (wrong-number-of-arguments (6 . 7) 8)
```

**Comment by beem812** [comment]
I'm also getting this error for what it's worth

**Comment by dschrempf** [comment]
For reference: https://github.com/wandersoncferreira/code-review/issues/227

**Comment by rlister** [comment]
Fixed for me, thank you :+1:

**Comment by wandersoncferreira** [comment]
Reopen if issue persist please. Thank you for your patiences.

**Comment by andycandy-dev** [comment]
I'm facing this issue with
`code-review 20221206.113`

UPD: perhaps this would be helpful
```
GNU Emacs 29.0.50 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6 (Build 21G115))
```

**Comment by chrislain-razafimahefa-sonarsource** [comment]
I am still facing this issue too. And this is what I get in `code-review-error.log`:
`code-review--build-buffer - (wrong-number-of-arguments (6 . 7) 8)`

**Comment by cwdjankoski** [comment]
also experiencing similar errors after calling `code-review-forge-pr-at-point` i get:  
```
deferred error : (wrong-type-argument listp 8)
```
from `code-review-error.log`:  
```
Sun Dec 25 16:42:41 2022 - code-review--build-buffer - (wrong-number-of-arguments (8 . 8) 6)
```

with
```
code-review  20221206.113
```

on  
```
GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-09-12
```

**Comment by andycandy-dev** [comment]
@wandersoncferreira should we open a new issue?
