### ISSUE TITLE
Support HTTP private instances

### ISSUE THREAD

**Issue by AustinMooreT** [wandersoncferreira/code-review#232]
My private gitlab instance uses http not https. There are two main issues I run into when trying to get code-review start to work.

- Firstly, functions like ghub-request look at a variable ghub-insecure-hosts to override https and use http instead. To fix that I just had to set that variable. I think I can just update the documentation to make that clear for others.
- Secondly, code-review-utils-pr-from-url is hardcoded to https. I think ideally this could do a similar check to ghub-requests and reuse the ghub-insecure-hosts variable as an override, or should I create a second code-review-insecure-hosts variable and use it instead? I'm not sure what's best practice when it comes to large elisp projects, so suggestions are welcome.

**Comment by wandersoncferreira** [comment]
Closing the issue as #233 was merged, thanks for taking the matter into your own hands and fixing it.
