### ISSUE TITLE
`code-review-start` and others give `deferred error : (wrong-type-argument sequencep #<subr code-review-section--magit-diff-insert-file-section>)`

### ISSUE THREAD

**Issue by mcamou** [wandersoncferreira/code-review#241]
**Describe the bug**

Whenever I try to start a code review I get the following error:

```
Fetch diff PR...80% 
deferred error : (wrong-type-argument sequencep #<subr code-review-section--magit-diff-insert-file-section>)
```

This is regardless of whether I use `code-review-start`, `code-review-forge-pr-at-point` or `+magit/start-code-review`.

**To Reproduce**
1. Run `M-x code-review-start`
2. Enter the URL of a pull request
3. See error

**Expected behavior**
The pull request review interface should show up

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: GNU Emacs 28.1 with Doom Emacs

**Comment by iamjarvo** [comment]
@mcamou I was also getting this error but after upgrading to the latest `doom` the error went away. Maybe try upgrading to see if the error disappears.

```
GNU Emacs     v28.2            nil
Doom core     v3.0.0-pre       HEAD -> master 92c9e93ed 
Doom modules  v22.10.0-pre     HEAD -> master 92c9e93ed
```

**Comment by mcamou** [comment]
Thanks @iamjarvo. I just updated doom and all packages. After doing `doom upgrade` I had some trouble with sqlite not being compiled so I wiped the straight directory and ran `doom sync -u`. I'm still having the same problem.

```
GNU Emacs     v28.1            nil
Doom core     v3.0.0-pre       HEAD -> master 788e507d4 2023-02-22 00:46:47 -0500
Doom modules  v22.10.0-pre     HEAD -> master 788e507d4 2023-02-22 00:46:47 -0500
```

This is the list of commits between your version of doom and mine:

```
$ git log --oneline 92c9e93ed..788e507d4
788e507d4 (HEAD -> master) fix(java): errors in company-yasnippet snippet previews
8b86ad318 docs(tree-sitter): document flags
40905d2c5 feat(tree-sitter): add support for more langs
63fac4fc6 bump: :tools tree-sitter
0469cc4c4 docs(tree-sitter): document tree-sitter flags
fd7ac6710 feat(tree-sitter): add support for more languages
e578c0ecf docs(haskell): mention tree sitter flag
074528a89 feat(haskell): add tree-sitter support
5f9d0b0f8 bump: :tools tree-sitter
9e0809711 fix(cli): doctor: wrong-type-argument stringp error
8f50ead5c fix(lib): doom/bumpify-diff: remove duplicates
81aa98049 bump: :config
1040dd45b bump: :editor
34b89c79e bump: :tools
ba8bf1ab9 bump: :lang
45d25af43 fix(default): browse-project: stringp type error
c523cd0e9 fix(vc): browse-at-remote: codeberg support
33af29f7d feat(docs): use header-line for header info
733f85719 feat(org): new "cmd" link type
825458e03 refactor(org): use new :help-echo for kbd link
14bf87002 fix(org): support module link names with A-Z0-9
0f7f91750 docs(org): improve links in readme
c1361c0ed feat(org): add some :help-echo for some links
181540c8b feat(org): introduce doom-executable link type
c26d64c9b feat(org): fancy docs links with activation fns
eed6d9058 fix(vc): string type error caused by codeberg support
344178c20 fix(vertico): docker-tramp => tramp-container
```

In theory there should not be a difference but... could you go into your `.emacs.d/.local/straight/build-28.2/code-review` and run `git log -1 --oneline`? This is the version of `code-review` that I'm running:

```
$ git log -1 --oneline
788e507d4 (HEAD -> master) fix(java): errors in company-yasnippet snippet previews
```

**Comment by andycandy-dev** [comment]
issue same as https://github.com/wandersoncferreira/code-review/issues/240
resolved by unpinning `code-review` at doom `packages.el` https://github.com/doomemacs/doomemacs/issues/6987

**Comment by mcamou** [comment]
Thanks @shroomist, that did it! Closing this one since it's a bug in Doom.
