### ISSUE TITLE
Experience for Evil users

### ISSUE THREAD

**Issue by wandersoncferreira** [wandersoncferreira/code-review#28]

**Comment by elken** [comment]
Testing this in doom now; curious what evil bindings weren't working for you @agzam. ootb evil seems to work fine without your snippet.

**Comment by elken** [comment]
Can confirm @agzam's snippet works fine. Will likely be refactored during review on doom's end though.

**Comment by wandersoncferreira** [comment]
How is the best way to move forward to improve Evil experience for users of this package? Add these bindings automagically? README entry pointing out what can be done? PR to evil-collection package?

I have zero experience with `evil-mode` but I am willing to learn enough to make this less painful.

**Comment by elken** [comment]
I was thinking about this myself when I was adding it, I think the best way would be to upstream to `evil-collection`.

As for what, most of what's defined in the magit map, anything that's relevant at least.

**Comment by agzam** [comment]
I recently switched from Spacemacs to Doom. The snippet above works fine. I think it could be safely added directly into the `code-review` source; It just needs to be wrapped into `(with-eval-after-load 'evil-collection)` block.

Alternatively, it could be noted in the Readme, the snippet is small enough, Evil users can grab it and add in their configs.

**Comment by elken** [comment]
No doubt that it couldn't, but it would definitely be better to PR against `evil-collection`.

**Comment by agzam** [comment]
@elken And what do you suggest this PR in evil-collection repo should offer? The above snippet "as is"? Because for 99% essential evil navigation in `code-review`, that's sufficient. I'm afraid they may say: "you can't cheat it like that for every package that's built on top of 'magit-section'"

**Comment by elken** [comment]
> And what do you suggest this PR in evil-collection repo should offer?
The same as any other package would.

> Because for 99% essential evil navigation in code-review, that's sufficient

And what's the haste? Getting the 100% is better than a "FIXME: later" snippet :) 

> I'm afraid they may say: "you can't cheat it like that for every package that's built on top of 'magit-section'"
It's not "cheating", it's a package that leverages magit but it is a distinct area that offers different functionality.

Before it's mentioned, I'm not even suggesting you or @wandersoncferreira do it, I'm happy to add it myself in the next week or so. Better to do something right once than hacky twice :)

**Comment by agzam** [comment]
@wandersoncferreira btw, setting up `k` (as default) in `code-review-feedback-section-map` perhaps wasn't a good choice. It took me awhile to understand what's happening. Scrolling with evil keys: `j/k` now differs from `C-n/C-p` and arrows. It jumps back to the beginning of the section all of a sudden.

**Comment by wandersoncferreira** [comment]
Seems like no further action should be done in this package. Feel free to open a new issue to improve the state of things for Evil users if a new idea pops up.

**Comment by jakejx** [comment]
Just wanted to add that I required this additional line for keybindings to work properly:
```
(evil-make-overriding-map code-review-mode-map evil-default-state)
```

**Comment by agzam** [comment]
@jakejx That's interesting. Can you please tell what exactly does this fix? I've been using the package in Doom (but not via the official module, I have a custom one) and never seem to have any issues. Maybe I've been missing something? Thank you.
