### ISSUE TITLE
CI Status

### ISSUE THREAD

**Issue by agzam** [wandersoncferreira/code-review#37]
This is probably the upstream That probably should be handled upstream - in Forge-Topic mode, it should show the status of CI checks. Nevertheless, I think it would be nice to show that info in the header of the `*Code Review*` buffer as well.

**Comment by wandersoncferreira** [comment]
Small demo of this functionality is available here https://github.com/wandersoncferreira/code-review/commit/5fd586ab2f0036bad6333b478dfdda761db54a3a:
![Screen Shot 2021-11-06 at 1 12 23 AM](https://user-images.githubusercontent.com/17708295/140597506-9bbe25e8-fac9-402a-8ddb-2d0d80a52254.png)

![Screen Shot 2021-11-06 at 1 12 01 AM](https://user-images.githubusercontent.com/17708295/140597507-cc7aa256-4977-410a-aeb5-f418f4373860.png)

I was thinking to provide a posframe window with details on click or hover. wdyt?

**Comment by agzam** [comment]
This is beautiful! 

>  was thinking to provide a posframe window with details on click or hover. wdyt?

I don't know, I think you can just make it to open the relevant run in the browser window. Posframe buffers are cool, but do you really want to lose your mind, trying to satisfy both - GUI and terminal users?

**Comment by wandersoncferreira** [comment]
@agzam took some time but I like the result:

![Screen Shot 2021-12-06 at 11 39 01 PM](https://user-images.githubusercontent.com/17708295/144956111-ce005879-eb8d-4117-a6f0-ef2cc8a0313d.png)
