### ISSUE TITLE
wrong-type-argument number-or-marker-p nil

### ISSUE THREAD

**Issue by ktfleming** [wandersoncferreira/code-review#51]
Hi, this package looks very cool! Trying it out on a test PR, I'm getting `wrong-type-argument number-or-marker-p nil` when calling `code-review-comment-add-or-edit` on a change. The full backtrace is

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  magit-diff-paint-tab(nil 8)
  magit-diff-paint-hunk(#<magit-hunk-section ((value nil (0 0) (1)) (path . "test.txt") (head-pos . 29)) [hunk file review-buffer] 508-[522-]555>)
  magit-section--maybe-wash(#<magit-hunk-section ((value nil (0 0) (1)) (path . "test.txt") (head-pos . 29)) [hunk file review-buffer] 508-[522-]555>)
  magit-section-show(#<magit-hunk-section ((value nil (0 0) (1)) (path . "test.txt") (head-pos . 29)) [hunk file review-buffer] 508-[522-]555>)
  magit-section-show(#<magit-file-section "test.txt" [file review-buffer] 488-[508-]555>)
  magit-section-show(#<magit-section nil [review-buffer] 1-555>)
  code-review--trigger-hooks("*Code Review*" nil nil)
  code-review--build-buffer("*Code Review*")
  #f(compiled-function (obj) "Commit the reply OBJ." #<bytecode -0xe97b3bb8284f427>)(#<code-review-local-comment-section nil [nil] nil-nil>)
  apply(#f(compiled-function (obj) "Commit the reply OBJ." #<bytecode -0xe97b3bb8284f427>) #<code-review-local-comment-section nil [nil] nil-nil> nil)
  code-review-comment-handler-commit(#<code-review-local-comment-section nil [nil] nil-nil>)
  code-review-comment-commit()
  funcall-interactively(code-review-comment-commit)
  command-execute(code-review-comment-commit)
```

The PR that's causing the error is https://github.com/ktfleming/code-review-bug/pull/1. Specifically, calling `code-review-comment-add-or-edit` on the `test.txt` change/added file causes the error, while calling it on the `README.md` change doesn't cause an error.

**Comment by wandersoncferreira** [comment]
Thanks @ktfleming for reporting the bug and providing the steps to reproduce the error.

I was only able to reproduce the error if I had `toggle-debug-on-error` activated and the error seems to be unrelated to adding a comment and more on `Magit-section` and `Magit-diff` interaction under the cover. Could you verify if disabling the `toggle-debug-on-error` will make the code continue to work? I will dig further to verify what is the root cause of this issue.

**Comment by wandersoncferreira** [comment]
@ktfleming please feel free to reopen this issue if the problem persist. Idk exactly how much time MELPA takes to update the package, but probably +3hrs or something like that.

**Comment by ktfleming** [comment]
I can confirm that it works now, thanks for the quick fix!
