### ISSUE TITLE
Approve without commenting

### ISSUE THREAD

**Issue by draxil** [wandersoncferreira/code-review#59]
In our workflow we don't really leave a comment for uncontroversial PRs, and often the dialog is elsewhere. 

As far as I can tell this package always forces me to leave a comment, even if it's the "LGTM" one. 

I'd be happy if it were a similar "shortcut" to LGTM, "approve without comment" or whatever. But perhaps this is easy for me to achieve and I'm missing something obvious?

This package is fantastic by the way :)

**Comment by wandersoncferreira** [comment]
Thanks @draxil !

In fact I miss interpreted the Github behavior on this.. if you Approve the PR you can leave it without comment and if you Request Changes or Comment a PR you are required to give some feedback.

I saw this screen and I thought every case had the same behavior. Thanks for reporting!
<img width="1250" alt="Screen Shot 2021-11-25 at 11 28 55 AM" src="https://user-images.githubusercontent.com/17708295/143459324-6e1e02db-61ad-492c-901a-2812162850ec.png">

**Comment by wandersoncferreira** [comment]
@draxil , it should be working as you expected now. Please let me know how it goes. Thanks again for reporting the issue.

**Comment by draxil** [comment]
@wandersoncferreira Fantastic! Works great. Amazing response time on that ;)
