### ISSUE TITLE
Error in code-review-start

### ISSUE THREAD

**Issue by seagle0128** [wandersoncferreira/code-review#62]
I got this error while running `code-review-start`.
I am using Emacs 29.0.50 on macOS Monterey.

```lisp
code-review--build-buffer - (wrong-type-argument listp error)
```

**Comment by wandersoncferreira** [comment]
@seagle0128 is it possible to give more information about the issue e.g. the URL you sent to `code-review-start` and the stack trace of this error?

This looks like Github returned an error message with a different shape than expected in this package. Could you update the package to run latest version in MELPA and look at the log entry in `~/.emacs.d/code-review-error.log`?
I just updated the package to log raw errors from Github so we can take a look at this.

**Comment by seagle0128** [comment]
I am using code-review-20211126.1005 on macOS.  The example URL is `https://github.com/wandersoncferreira/code-review/pull/50`. There is no stack trace, and only this meesage `Got an error from your VC provider. Check ‘code-review-log-file’.`

Only this error in `~/.emacs.d/code-review-error.log`.
```
Sat Nov 27 03:00:15 2021 - code-review--build-buffer - (wrong-type-argument listp error)
```

**Comment by hungpham2511** [comment]
I have the same issue and turns out it's because I have not added the personal key in the authentication file.

The error message can be made more informative I think.

Checking the results for errors https://github.com/wandersoncferreira/code-review/blob/b8bb2394ad19a639d16a7960849ab7ddfc8eda78/code-review.el#L212 here should do it.

**Comment by wandersoncferreira** [comment]
Thanks for the info @hungpham2511 , should be fixed now. @seagle0128 could you confirm that this fixes your error too?

**Comment by seagle0128** [comment]
Thank you! It's working. Closing it.
