### ISSUE TITLE
Tighter connection with magit/forge?

### ISSUE THREAD

**Issue by magthe** [wandersoncferreira/code-review#77]
**Is your feature request related to a problem? Please describe.**
I was surprised to see that `code-review` seems to be completely separate from `magit`/`forge`. I can already work with PRs using `forge` so it'd be really nice if `code-review` hooked into that somehow, e.g. a key combo that, similar to `C-c Ce` (`magit-edit-thing`), let me start a review when looking at a PR.

**Describe alternatives you've considered**
I jumped into git status, opened one of the existing PRs, and ran `M-x code-review-start`, then I was asked for the URL of a PR.

**Comment by ktfleming** [comment]
Jumping in here just as another user, but maybe `code-review-forge-pr-at-point` is what you want? If you run that with point on a Forge PR in the magit-status buffer, it should start the code-review process without you needing to give it a URL.

**Comment by magthe** [comment]
Ah, yes, that seems to do what I want.

Now I just have to sort out the integration with evil so that not all key combos aren't shadowed by other things.
